site_name: bim-GDPR
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust

nav:
    - Home: './index.md'
    - General :
        - Why should you care about customization : './general/about.md'
        - Structure: './general/structure.md'

    - Getting started:
        - Use NPM: ./start/npm.md
        - Use CDN: ./start/cdn.md
        - Declare services: ./start/declare.md

    - Events: 
        - Introduction : ./events/principle.md
        - Service events: ./events/service_events.md
        - View events: ./events/view_events.md
        - Group events: ./events/group_events.md

    # - Core settings: ./core/core.md

    - Services : 
        - Introduction : './services/index.md'
        - Create a service: './services/create.md'
        - Service methods : './services/methods.md'

    - Templates : 
        - Introduction : './template/index.md'
        - Create a template: './template/create.md'
        - Template methods : './template/methods.md'

    - Groups : 
        - Introduction : ./groups/index.md

    - Translations:
        - Introdution: ./translations/index.md

    - Placeholders :
          - Introdution: ./placeholders/index.md

    - How to ...:
        - Force the displayed language: './how/force-language.md'
    
