site_name: bim-GDPR
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust

nav:
    - Home: './index.md'
    - General :
        - Why should you care about customization : './general/about.md'
        - Structure: './general/structure.md'

    - Getting started:
        - Installation: ./start/install.md
        - Initialisation: ./start/init.md
        - Declare service: ./start/declare.md

    - Events: 
        - Introduction : ./events/principle.md
        - Service events: ./events/service_events.md
        - View events: ./events/view_events.md
        - Group events: ./events/group_events.md

    # - Core settings: ./core/core.md

    - Services : 
        - Introduction : ./services/index.md
        - Create a reusable service: './services/create.md'
        - Service methods : './services/methods.md'

    - Templates : 
        - Introduction : ./templates/index.md
        - Create a template: './templates/create.md'
        - Template methods : './templates/methods.md'

    - Groups : 
        - Introduction : ./groups/index.md

    - Translations:
        - Introdution: ./translations/index.md

    - How to ...:
        - Force the displayed language: './how/force-language.md'
    
